environment:
  global:
    PROJECT_NAME: rpp-nudger
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    MSYS2_BITS: 64
  - TARGET: i686-pc-windows-gnu
    MSYS2_BITS: 32
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

# ???
build: false

before_deploy:
  # Generate artifacts for release
  - cargo build --release --target %TARGET%
  - mkdir staging
  - copy target\%TARGET%\release\%PROJECT_NAME%.exe staging
  - cd staging
    # release zipfile will look like '%PROJECT_NAME%-v1.2.3-x86_64-pc-windows-msvc'
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: 'Windows release'
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  auth_token:
    secure: LwnCUuVi6YlhKOdDif/XgJkQ7MHwiAELreMYMQD6421T5Uq8il0vV1Xi35pn6hHT
  provider: GitHub

branches:
  only:
    - master